### ISSUE TITLE
Can this be modified to work with a UC300eth?

### ISSUE THREAD

**Issue by syagoda** [twentyfortysix/uccnc_screenset_2046#1]
I love this new screenset, I don't have a step craft machine, but an OXcnc. I am running a uc300eth, but after loading all of the files and running that profile, I just get a white screen with your screen set. If I run it in demo mode with the uc100, it works.

thanks.

**Comment by twentyfortysix** [comment]
Hi
Check this out
https://www.forum.cncdrive.com/viewtopic.php?f=9&t=3731&start=40#p26969

"ger21" describes how to update it for UC400ETH, I guess it'll be same in your case.
If you do it for yourself and test it and it works it would be awesome if you can share it with me and I add it to the bundle. 
I don't want to do it my self without real test on real machine.

**Comment by syagoda** [comment]
Ok, so I tried this on the demo and still just get a white screen when I use the UC400ETH.  If I change that to 300ETH,  I get an error in the demo. On my machine with my controller, I just get a white screen.  I notice that when it first loads, I don't get a green bar in the loading window, like with the regular screenset. I am not sure what I am missing, you would think it would work with any controller, the code looks exactly like the default screenset. 

Any help would be greatly appreciated, I am really trying to get this screenset working. I like the simple layout.

**Comment by twentyfortysix** [comment]
Hi

I don't know what have you done in the code and also don't know what exactly is needed for this transformation.. but I made a blind test you can get from here 
[Stepcraft_2046.ssf](https://gist.github.com/twentyfortysix/ec73ae3bc0188315359a23248dde1d01)
Just replace the file in Screens folder. If that does not work, we should ask for help on the uccnc forum, there might be somebody who actually hacked my Screenset for other controller already.

**Comment by syagoda** [comment]
<img width="316" alt="Screenshot 2023-01-12 183218" src="https://user-images.githubusercontent.com/7333284/212210178-2c93be41-d90e-48df-a758-8eff57e9e694.png">

This is the error I get, It is a similar error compared to when I tried it.

**Comment by twentyfortysix** [comment]
Hmm weirdly it looks like it went to a wrong part of the code.. to the UC100.
I have removed all the definitions [UC100, UC400ETH] from the file other than the definitions for UC300ETH.
Try it now... the same git.

**Comment by syagoda** [comment]
I redownloaded the file, but did not see any changes, it should just be the .ssf file correct?  I tried to change mine and replaced UC100 with UC300ETH_LPT, but this only gives me an error on line 6405. 
<img width="294" alt="Screenshot 2023-01-13 172739" src="https://user-images.githubusercontent.com/7333284/212437208-a5853abd-d3dc-4b8b-9364-18745521ac41.png">

**Comment by twentyfortysix** [comment]
Yes what I wanted you to do is to just replace the Stepcraft_2046.ssf with its new shortened version from git.
Because it looked like the program went to wrong "if" statement and did not found the correct one located further down the file.

First
Now if even after you tried the new shortened version and you receive the same error
https://user-images.githubusercontent.com/7333284/212210178-2c93be41-d90e-48df-a758-8eff57e9e694.png
Then I do not understand why is that so. As it says it cannot find the ETH300 definition, which is clearly not correct.

Second
The error you have now is a typo in the file you have edited, some extra ' or ` on the 6405 line.

**more thoughts:**

I still do not understand why it says that there is no ETH300 definition while the code says:

`if (mainform.userselecteddevtype == UC100.DeviceType.UC300ETH || mainform.userselecteddevtype == UC100.DeviceType.Demo_UC300ETH)`

I rechecked the .ssf file and there is nothing crucial really. The file is divided by IFs for specific controllers and inside the IFs there are only buttons defined plus something little bit more. That can basically be all the same only the IF statements are different as in the controller name. The reason why is that like this is that some controllers might not support some feature and so the screenset can be adjusted here.. like buttons removed etc. But gain nothing crucial.

The problem remains. Why the program even went to line 12 when the if states that this part of the code is for different controller than you have defined by the IF statement:

`if (mainform.userselecteddevtype == UC100.DeviceType.Demo_mode || mainform.userselecteddevtype == UC100.DeviceType.Demo_UC100 || mainform.userselecteddevtype == UC100.DeviceType.UC100)`

I guess there must be some naming mismatch in the controllers you use, just a guess.

The default screenset has no EC300ETH defined at all.
it has these:
//REGION UC300ETH_5LPT
//REGION UC300ETH_5441
//REGION UC300ETH_M44
//REGION UC300ETH_M45
//REGION UC300ETH_UB1

What I believe now is that you must name your controlled bit more specifically .. hopefully you have some of those as if the default works for you it must be one of them.
(What I also believe is that the UCCNC wrongly parses the names of the controllers while it walks thru if statements.. but that is nothing we can fix)

**Comment by twentyfortysix** [comment]
And it looks like my guess is correct
https://www.forum.cncdrive.com/viewtopic.php?f=9&t=3731&start=50#p29488

**Comment by syagoda** [comment]
Ok, I could not find the .ssf  that was updated the other day, all the ones I say had the older dates. I just downloaded the new one and changed all the UU400's to UC300ETH_5LPT. I am get an unexpected error on line 3038 for an unexpected character, but I don't see anything extra there.  With those changes I can rum the UC100 DEMO and it loads fine. If I try the UC400 Demo it just gives me a white screen. I think we are getting closer.  Is there a way to share the updated file with you on here?

**Comment by twentyfortysix** [comment]
Hi 
once you have github, the easiest way might be to create a gist as I did just go to your https://gist.github.com/syagoda and create a gist.
The code checker is not always right. It might a line higher or somewhere else :)
Anyway, send me the file you have now, and also the error you get, when ever you get error send it to me, even if it might seems like repetition to you, that way I will know what's going on and I might see what you do not notice.

btw the only thing we need to get right is the naming in the if statement

`
if (mainform.userselecteddevtype == UC100.DeviceType.UC300ETH_5LPT || mainform.userselecteddevtype == UC100.DeviceType.Demo_UC300ETH_5LPT)`

everything else should stay as is.. I guess you know that.

**Comment by syagoda** [comment]
Ok, I created the gist, the error code I am getting now is this.  
<img width="296" alt="Screenshot 2023-01-14 114104" src="https://user-images.githubusercontent.com/7333284/212487430-55d04c49-6aa3-4e72-afd3-f5c2193009a6.png">

**Comment by twentyfortysix** [comment]
see the line 6401
you gonna find this 

AS3.Addcodeview("", "Arial", "left", 16, -1, 670, 274, 206, `54, 45);

there is a tick before 54.. I think that it is the problem.. if not it would be in future anyway .]
Delete it and try it again.

**Comment by syagoda** [comment]
Check out the newest one I just put up, That was the updated one you had uploaded, It looks like it loads, I don't get a green bar when it is preparing, and then just get a white screen, but I hear the sound when it loads.  I even have to click yes when I get the prompt if I want to exit.

**Comment by syagoda** [comment]
Check out the 3rd revision, I removed all other controllers from the file along with their sections. Now it will load, but it is the original step craft screen set. This is weird because everything still says step craft _2046.  I feel like I am getting close since it will load, just can't figure out why it is defaulting to the other screen set.

**Comment by twentyfortysix** [comment]
Yo :)
check out the last line of the file
AS3.Addlabel("X", "Arial", "left", 12, -12566464, 57, 233, 30);
it's clearly not a proper end of the file. If anything else the IF should be closed with }.. anyhoots.

Now knowing what controller we have and also that there is a tick somewhere that causes white screen of  dead I went back to my original Screenset file changed the controller name and checked for the `.
And sure there was one and it is my mistake, I'm sorry for that and thank you that you found it.

I have updated the gist https://gist.github.com/twentyfortysix/ec73ae3bc0188315359a23248dde1d01
and if there is no other problem these 2 should be covered.

Let me know.

**Comment by syagoda** [comment]
OK, So that one worked with UC100, but still not the UC300, I did notice it was missing the _5LPT. Once I added that to the first few lines and the last line, it opens. It however just gets a white screen with the UC100 demo now. Later on today, I hope to test it on my machine computer and see if everything works.  I apologize for all the files added to the gist, this is my first time using Github.

**Comment by twentyfortysix** [comment]
Hi, 
no problem with the files on github.

I'm not sure what you mean by "OK, So that one worked with UC100," I believe you talk about some previous version, not the last one I have updated on gist https://gist.github.com/twentyfortysix/ec73ae3bc0188315359a23248dde1d01.
The link is the same, I'm just updating the same file.
I'm still not on machine yet, plus I do not have the UC300ETH_5LPT and so the problem never occurred to me as the program never went to that part of the code where it has some problem.

Anyway.. let me know once you test my latest gist and make sure you reloaded the gist page if you have that opened from previous time.. so that you do not use some old cached version.

_I think I'm gonna be on Machine during the week, but I'm afraid that it will be of no help while I do not have UC300ETH_5LPT._

**Comment by syagoda** [comment]
Ok, success, it works perfectly on my machine with the UC300_5LPT.  I was able to get all the axis to move, along with homing and TLS.  I am going to try and run a cut and see how things good.  Here is the final file that I am currently using.  Thanks again for all of your help. 

Justin 
[Stepcraft_2046.zip](https://github.com/twentyfortysix/uccnc_screenset_2046/files/10420775/Stepcraft_2046.zip)

**Comment by twentyfortysix** [comment]
Nice.
The functions are not different from the Stepcraft's version. The only thing that is defined in this Screenset are buttons, 3D view and text fields positions and it corresponding images.
I hope you find this screenset more practical and help you to control your machine without hassle.

Thanks for test, and let me know if there is anything it should be made better .]

**Comment by twentyfortysix** [comment]
Hi
Can you try this Screenset?
https://gist.githubusercontent.com/twentyfortysix/12a93fbd43369d4d3a345ff43639e947/raw/882af54b9e491a38cd9ed097930e92066263b79f/Stepcraft_2046.ssf

it is quite huge, it consists of all controllers the UCCNC supports, including yours (I tried it on my machine and it is OK).
Let me know if it works for you.
thank you

**Comment by syagoda** [comment]
Good afternoon, sorry for the delay, I have been a little under the weather.  I just tested this one on my machine and it works great. Great Job!  Thanks for all of your work on this, love this new screenset, it is a lot easier to navigate. 

Thanks,
  Justin

**Comment by twentyfortysix** [comment]
thank you for testing
